# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geneID_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('Knockout', 'KNOCKOUT'), ('Regulation', 'REGULATION')], max_length=15)),
                ('geneID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crispr_app.GeneID')),
            ],
        ),
    ]
