# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crispr_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RNA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.CharField(max_length=30)),
                ('species', models.CharField(max_length=20)),
                ('zero_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('one_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('two_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('three_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('four_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('five_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('six_mismatch_count', models.IntegerField(blank=True, null=True)),
                ('off_target_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
